[package]
name = "lichess-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Dependencies for awc lichess client.
actix-web = { version = "4.2.1", optional = true }
awc = { version = "3.0.1", features = ["rustls"], optional = true }
webpki-roots = { version = "0.22.6", optional = true }
mime = { version = "0.3.16", optional = true }
rustls = { version = "0.20.8", optional = true }

# Dependencies for reqwest lichess client.
reqwest = { version = "0.11.13", features = ["json", "stream"]}

# Other dependencies.
async-std = "1.12.0"
bytes = "1.3.0"
futures = "0.3.25"
futures-core = "0.3.25"
http = "0.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_with = { version = "2.2.0", features = ["chrono"] }
serde_urlencoded = "0.7.1"
thiserror = "1.0.38"
url = "2.3.1"

[dev-dependencies]
tokio = { version = "1.24.2" , features = ["macros", "rt-multi-thread"] }

[features]
awc = ["dep:actix-web", "dep:awc", "dep:webpki-roots", "dep:mime", "dep:rustls"]
